STAFF_IDS:
  Bram van Ginneken:
    - 8038506
    - 123637526
    - 2238811617
    - 2237665783
    - 2064076416
  Francesco Ciompi:
    - 143613202
    - 2246376566
    - 2291304571
    - 2370540204
  Alessa Hering:
    - 153744566
  Henkjan Huisman:
    - 34754023
    - 2247422768
    - 2242473717
    - 2275450757
  Colin Jacobs:
    - 2895994
    - 2281807058
    - 2331492473
    - 2262970009
    - 2368325830
  Peter Koopmans:
    - 34726383
  Jeroen van der Laak:
    - 145441238
    - 145388932
    - 2347447
    - 2255290517
    - 2259038560
  Geert Litjens:
    - 145959882
  James Meakin:
    - 4960344
  Keelin Murphy:
    - 35730362
  Ajay Patel:
    - 2109170880
    - 2116215861
  Cornelia Schaefer-Prokop:
    - 1419819133
    - 1445069528
    - 1400632685
    - 2242581221
    - 2262278647
    - 2240604857
    - 2250313247
  Matthieu Rutten:
    - 2074975080
    - 2156546
    - 47920520
    - 2238355627
    - 2239745868
  Jos Thannhauser:
    - 5752941
  Bram Platel:
    - 1798137
  Nico Karssemeijer:
    - 1745574
  Clarisa Sanchez:
    - 144085811
    - 32187701
  Nikolas Lessman:
    - 2913408
  Jonas Teuwen:
    - 32649341
    - 119024451
    - 2259899370
  Rashindra Manniesing:
    - 2657081
  Nadieh Khalili:
    - 144870959

STAFF_YEARS:
  Bram van Ginneken:
    start: 1996
    end: 9999
  Francesco Ciompi:
    start: 2013
    end: 9999
  Alessa Hering:
    start: 2018
    end: 9999
  Henkjan Huisman:
    start: 1992
    end: 9999
  Colin Jacobs:
    start: 2010
    end: 9999
  Peter Koopmans:
    start: 2022
    end: 9999
  Jeroen van der Laak:
    start: 1991
    end: 9999
  Geert Litjens:
    start: 2016
    end: 9999
  James Meakin:
    start: 2017
    end: 9999
  Keelin Murphy:
    start: 2018
    end: 9999
  Ajay Patel:
    start: 2015
    end: 9999
  Cornelia Schaefer-Prokop:
    start: 2010
    end: 9999
  Matthieu Rutten:
    start: 2019
    end: 9999
  Jos Thannhauser:
    start: 2022
    end: 9999
  Bram Platel:
    start: 2010
    end: 2019
  Nico Karssemeijer:
    start: 1989
    end: 2022
  Clarisa Sanchez:
    start: 2008
    end: 2021
  Nikolas Lessman:
    start: 2019
    end: 2022
  Jonas Teuwen:
    start: 2017
    end: 2020
  Rashindra Manniesing:
    start: 2010
    end: 2021
  Nadieh Khalili:
    start: 2023
    end: 9999